spring.application.name=CollabCodeEditor
server.port=8383

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/pcce
spring.datasource.username=supervisor
spring.datasource.password=supervisor351
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Settings (if using Spring Data JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# MongoDB Configuration
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=mcce
spring.data.mongodb.username=muser
spring.data.mongodb.password=mpassword

#JWT Secrect Key
spring.config.import=optional:file:./application-secrets.properties

# Generated JWT token expires in 15 minutes
collab.jwtExpirationMs=900000

