name: CI Pipeline

on:
  push:
    branches:
      - dev
      - uat
      - main
  pull_request:
    branches:
      - dev
      - uat
      - main

jobs:
  backend-build:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend/CollabCodeEditor
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Make mvnw executable
        run: chmod +x ./mvnw
      - name: Build with Maven
        run: ./mvnw clean install

  frontend-build:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install
      - name: Run Build
        run: npm run build
      - name: Run Tests
        run: npm test -- --watchAll=false

  promote-to-uat:
    name: Promote Dev to UAT
    runs-on: ubuntu-latest
    needs:
      - backend-build
      - frontend-build
    # Run this job only when the branch is dev
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}  # Uses the automatically generated GITHUB_TOKEN
          fetch-depth: 0  # Ensure full history for merging
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
      - name: Merge Dev into UAT
        run: |
          # Check if the uat branch exists; if not, create it
          git checkout uat || git checkout -b uat
          # Merge dev into uat with a merge commit
          git merge dev --no-ff -m "Auto-merge from dev to uat"
          # Push the updated uat branch to origin
          git push origin uat
